### ISSUE TITLE
MegEngine 1.9.0 causes test.py error

### ISSUE THREAD

**Issue by MartinPeris** [megvii-research/CREStereo#13]
I have been playing around a bit with the code (thank you so much, by the way. Having heaps of fun with it) and found out that MegEngine 1.9.0 causes test.py to die with the following output:

```
Images resized: 1024x1536
Model Forwarding...
Traceback (most recent call last):
  File "test.py", line 94, in <module>
    pred = inference(left_img, right_img, model_func, n_iter=20)
  File "test.py", line 45, in inference
    pred_flow_dw2 = model(imgL_dw2, imgR_dw2, iters=n_iter, flow_init=None)
  File "/usr/local/lib/python3.6/dist-packages/megengine/module/module.py", line 149, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/dgxmartin/workspace/CREStereo/nets/crestereo.py", line 210, in forward
    align_corners=True,
  File "/usr/local/lib/python3.6/dist-packages/megengine/functional/vision.py", line 663, in interpolate
    [wscale, Tensor([0, 0], dtype="float32", device=inp.device)], axis=0
  File "/usr/local/lib/python3.6/dist-packages/megengine/functional/tensor.py", line 405, in concat
    (result,) = apply(builtin.Concat(axis=axis, comp_node=device.to_c()), *inps)
TypeError: py_apply expects tensor as inputs
```

For the time being the MegEngine version should be set to exactly 1.8.2

**Comment by yanziwei** [comment]
Replacing MegEngine 1.9.0 to MegEngine 1.8.2 works perfectly

**Comment by Dipeshtamboli** [comment]
Hi, 

I cannot have 1.8.2 version now. 

`$ pip3 install MegEngine==1.8.2`

> ERROR: Could not find a version that satisfies the requirement MegEngine==1.8.2 (from versions: 1.12.3, 1.12.4)
> ERROR: No matching distribution found for MegEngine==1.8.2

**Comment by MartinPeris** [comment]
The latest main branch requries MegEngine >= 1.9.1 which is supposed to solve this issue and some others: https://github.com/megvii-research/CREStereo/pull/24 

Doesn't it work for you?
