### ISSUE TITLE
RuntimeError: bad input shape for polyadic operator

### ISSUE THREAD

**Issue by yangxiaohhh** [megvii-research/CREStereo#32]
请问有人遇到这个问题吗？这是我在尝试训练时出现的，我想这应该是数据集设置不对，是否有人管知道这如何修改呢
环境：windows 10
旷视版本：mge1.8.2
> err: failed to load cuda func: cuDeviceGetNvSciSyncAttributes
> 2022/08/04 11:50:55 Use 1 GPU(s)
> 2022/08/04 11:50:55 Params: 5432948
> 2022/08/04 11:50:55 Dataset size: 5000
> Traceback (most recent call last):
>   File "c:/CREStereo-master/train.py", line 309, in <module>
>     run(args)
>   File "c:/CREStereo-master/train.py", line 207, in main
>     flow_predictions = model(left, right)
>   File "C:\Users\wd\AppData\Local\Programs\Python\Python38\lib\site-packages\megengine\module\module.py", line 149, in __call__
>     outputs = self.forward(*inputs, **kwargs)
>   File "c:\CREStereo-master\nets\crestereo.py", line 263, in forward
>     out_corrs = corr_fn(flow, None, small_patch=small_patch, iter_mode=True)
>   File "c:\CREStereo-master\nets\corr.py", line 25, in __call__
>     corr = self.corr_iter(self.fmap1, self.fmap2, flow, small_patch)
>   File "c:\CREStereo-master\nets\corr.py", line 72, in corr_iter
>     corr = self.get_correlation(
>   File "c:\CREStereo-master\nets\corr.py", line 48, in get_correlation
>     corr_mean = F.mean(left_feature * right_slid, axis=1, keepdims=True)
>   File "C:\Users\wd\AppData\Local\Programs\Python\Python38\lib\site-packages\megengine\core\tensor\array_method.py", line 176, in f
>     return _elwise(self, value, mode=mode)
>   File "C:\Users\wd\AppData\Local\Programs\Python\Python38\lib\site-packages\megengine\core\tensor\array_method.py", line 73, in _elwise      
>     return _elwise_apply(args, mode)
>   File "C:\Users\wd\AppData\Local\Programs\Python\Python38\lib\site-packages\megengine\core\tensor\array_method.py", line 36, in _elwise_apply    (result,) = apply(op, *args)
> RuntimeError: bad input shape for polyadic operator: {2,64,128,96}, {18,64,128,96}
> 
> backtrace:
> 2 null
> 
> 3 null
> 
> 4 null
> 
> 5 null
> 
> 6 null
> 
> 7 null
> 
> 8 null
> 
> 9 null
> 
> 10 null
> 
> 11 null

**Comment by suxingzhao** [comment]
ME TOO.WHY?

**Comment by Sheldonmao** [comment]
I run into the same problem with MegEngine 1.11.0 on Ubuntu. Any idea how to fix it?

**Comment by Sheldonmao** [comment]
> I run into the same problem with MegEngine 1.11.0 on Ubuntu. Any idea how to fix it?

I managed to run the code by reducing `batch_size_single` to 1 in `configs/train.yaml`. It seems the current code doesn't support a batch size greater than 1, restricted by the broadcasting mechanism.

**Comment by WeihongPan** [comment]
我也碰到了，一模一样，用提供的数据集也会报这个错误

**Comment by LiuPearl1** [comment]
Meet same problem. Did anyone fix this problem?

**Comment by philleer** [comment]
Same issue, does anyone have some idea?

**Comment by zyl1336110861** [comment]
+1

**Comment by zza1617** [comment]
+1

**Comment by YonatanSimson** [comment]
Same issue. The error comes from line: `F.mean(left_feature * right_slid, axis=1, keepdims=True)`

right_slid for some strange reason get's the number of channels changed to 18. Why 18? 2 * 9 = 18. Since the batch size is 2 and the number of correlations we are carrying out is either 3x3 for a patch or 1x9 for a line.

I did a bit of a hack to fix it:

In the file nets/corr.py replace lines 47-50 with this:

 
         right_pad = F.pad(right_feature, pad_width=(
            (0, 0), (0, 0), (pady, pady), (padx, padx)), mode="replicate")

        right_slid = F.sliding_window(
            right_pad, kernel_size=(H, W), stride=(di_y, di_x))  # N, C, 1, 9, H, W
        right_slid = right_slid.reshape(N, C, -1, H, W)  # N, C, 9, H, W
        right_slid = F.transpose(right_slid, (0, 2, 1, 3, 4))  # N, 9, C, H, W

        # This is buggy when trying to train with batch size larger than 1
        # right_slid = right_slid.reshape(-1, C, H, W)  # N * 9, C, H, W
        # corr_mean = F.mean(left_feature * right_slid, axis=1, keepdims=True)  # 9, N, H, W
        # corr_final = corr_mean.reshape(1, -1, H, W)  # N, 9, H, W

        Nr, num_slides, Cr, Hr, Wr = right_slid.shape

        corr_list = []
        for slide_idx in range(0, num_slides):
            right_crop = right_slid[:, slide_idx, :, :, :]
            assert right_crop.shape == left_feature.shape
            corr = F.mean(left_feature * right_crop, axis=1, keepdims=True)
            corr_list.append(corr)

        corr_final = F.concat(corr_list, axis=1)  # N, 9, H, W

**Comment by jeffabc1997** [comment]
> Same issue. The error comes from line: `F.mean(left_feature * right_slid, axis=1, keepdims=True)`
> 
> right_slid for some strange reason get's the number of channels changed to 18. Why 18? 2 * 9 = 18. Since the batch size is 2 and the number of correlations we are carrying out is either 3x3 for a patch or 1x9 for a line.
> 
> I did a bit of a hack to fix it:
> 
> In the file nets/corr.py replace lines 47-50 with this:
> 
> ```
>      right_pad = F.pad(right_feature, pad_width=(
>         (0, 0), (0, 0), (pady, pady), (padx, padx)), mode="replicate")
> 
>     right_slid = F.sliding_window(
>         right_pad, kernel_size=(H, W), stride=(di_y, di_x))  # N, C, 1, 9, H, W
>     right_slid = right_slid.reshape(N, C, -1, H, W)  # N, C, 9, H, W
>     right_slid = F.transpose(right_slid, (0, 2, 1, 3, 4))  # N, 9, C, H, W
> 
>     # This is buggy when trying to train with batch size larger than 1
>     # right_slid = right_slid.reshape(-1, C, H, W)  # N * 9, C, H, W
>     # corr_mean = F.mean(left_feature * right_slid, axis=1, keepdims=True)  # 9, N, H, W
>     # corr_final = corr_mean.reshape(1, -1, H, W)  # N, 9, H, W
> 
>     Nr, num_slides, Cr, Hr, Wr = right_slid.shape
> 
>     corr_list = []
>     for slide_idx in range(0, num_slides):
>         right_crop = right_slid[:, slide_idx, :, :, :]
>         assert right_crop.shape == left_feature.shape
>         corr = F.mean(left_feature * right_crop, axis=1, keepdims=True)
>         corr_list.append(corr)
> 
>     corr_final = F.concat(corr_list, axis=1)  # N, 9, H, W
> ```

I have the same issue but this solution didn't work out.

**Comment by jeffabc1997** [comment]
Hey guys, 
in test.py:
```
parser.add_argument(
        "--size",
        default="368x1240",
        help="The image size for inference. Te default setting is 1024x1536. \
                        To evaluate on ETH3D Benchmark, use 768x1024 instead.",
    )
```
The size should be 8's multiple. I changed this and it works!
Hope if this can help.

**Comment by jeffabc1997** [comment]
Hey guys, 

```
parser.add_argument(
        "--size",
        default="368x1240",
        help="The image size for inference. Te default setting is 1024x1536. \
                        To evaluate on ETH3D Benchmark, use 768x1024 instead.",
    )
```
The size should be 8's multiple. I changed this and it works!
Hope if this can help.

**Comment by NIKEmissa** [comment]
遇到了同样的问题，我把corr.py退回到上个commit版本，解决了这个保存。（优雅的办法还没找到，只能权宜之计了 /手动狗头

Just roll back corr.py to https://github.com/megvii-research/CREStereo/commit/aa9156e01b1bcf1685eb1d7ebbbe856940c67498
